import {  useState,  } from 'react'
import Head from 'next/head'
import Footer from '@/components/Footer'

import About from '@/components/About'
import Header from '@/components/Header'

const AboutPage = () => {
    const [showAddTask, setShowAddTask] = useState(false)
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container">
        <Header
          title="Task Tracker"
          onAdd={() => setShowAddTask(!showAddTask)}
          showAddTask={showAddTask}
        />
        <About />
        <Footer />
    </div>
  </>
  )
}

export default AboutPage