import { useContext, useState, useEffect } from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Tasks from '../components/Tasks'
import AddTaskForm from '../components/AddTaskForm'
import Footer from '../components/Footer'

import AppContext from '../context/app/appContext'

export default function Home() {
  const appContext = useContext(AppContext)

  const { getTasks, saveTasks, tasks } = appContext

  const [showAddTask, setShowAddTask] = useState(false)

  const [initLoad, setInitLoad] = useState(true)
  

  // componentDidMount
  useEffect(() => {
    const updateInitLoad = () => {
      setInitLoad(false)
    }

    getTasks()
    updateInitLoad()
    // eslint-disable-next-line
  }, [])

  // // componentDidUpdate
  useEffect(() => {
    // Only update after init load
    if (!initLoad) {
      saveTasks()
    }
  }, [tasks, initLoad])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header
          title="Task Tracker"
          onAdd={() => setShowAddTask(!showAddTask)}
          showAddTask={showAddTask}
        />

        <>
          {showAddTask && <AddTaskForm />}

          {tasks.length ? <Tasks tasks={tasks} /> : <h3>No Tasks</h3>}
        </>
        <Footer />
      </div>
    </>
  )
}
