export const GET_TASKS = 'GET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const SET_LOADING = 'SET_LOADING'
export const DELETE_TASK = 'DELETE_TASK'
export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const SAVE_TASKS = 'SAVE_TASKS'
